export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const SHOW_MORE = "SHOW_MORE";